package com.example.ialocal.models

/**
 * Curated GGUF downloads shown inside the app.
 *
 * Every entry below points to a real single-file GGUF that can be downloaded atomically by the
 * current downloader. Multi-part GGUFs and models that require an additional projection file for
 * their primary use are intentionally excluded until installation can manage a file set.
 */
data class CatalogModel(
    val id: String,
    val name: String,
    val variant: String,
    val description: String,
    val fileName: String,
    val approximateSizeBytes: Long,
    val downloadUrl: String,
    val source: String,
    val license: String,
    val recommended: Boolean = false,
) {
    val sourceUrl: String get() = "https://huggingface.co/$source"
}

object ModelCatalog {
    val items: List<CatalogModel> = listOf(
        CatalogModel(
            id = "qwen3-06b-q4-0",
            name = "Qwen3 0.6B",
            variant = "Q4_0 · 429 MB",
            description = "A opção mais leve do catálogo. Útil quando armazenamento e RAM são muito limitados.",
            fileName = "Qwen3-0.6B-Q4_0.gguf",
            approximateSizeBytes = 429_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q4_0.gguf?download=true",
            source = "ggml-org/Qwen3-0.6B-GGUF",
            license = "Apache-2.0",
        ),
        CatalogModel(
            id = "lfm2-12b-q4-k-m",
            name = "LFM2 1.2B",
            variant = "Q4_K_M · 731 MB",
            description = "Modelo compacto da Liquid AI voltado a execução eficiente em dispositivos de borda.",
            fileName = "LFM2-1.2B-Q4_K_M.gguf",
            approximateSizeBytes = 731_000_000L,
            downloadUrl = "https://huggingface.co/LiquidAI/LFM2-1.2B-GGUF/resolve/main/LFM2-1.2B-Q4_K_M.gguf?download=true",
            source = "LiquidAI/LFM2-1.2B-GGUF",
            license = "LFM 1.0",
            recommended = true,
        ),
        CatalogModel(
            id = "llama32-1b-q4-k-m",
            name = "Llama 3.2 1B Instruct",
            variant = "Q4_K_M · 808 MB",
            description = "Llama pequeno e instruído, adequado para aparelhos modestos e tarefas curtas.",
            fileName = "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
            approximateSizeBytes = 808_000_000L,
            downloadUrl = "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf?download=true",
            source = "bartowski/Llama-3.2-1B-Instruct-GGUF",
            license = "Llama 3.2 Community License",
        ),
        CatalogModel(
            id = "gemma3-1b-it-q4-k-m",
            name = "Gemma 3 1B IT",
            variant = "Q4_K_M · 806 MB",
            description = "Gemma 3 compacto e instruído. Boa alternativa leve para uso local em celular.",
            fileName = "gemma-3-1b-it-Q4_K_M.gguf",
            approximateSizeBytes = 806_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/gemma-3-1b-it-GGUF/resolve/main/gemma-3-1b-it-Q4_K_M.gguf?download=true",
            source = "ggml-org/gemma-3-1b-it-GGUF",
            license = "Gemma License",
        ),
        CatalogModel(
            id = "qwen3-17b-q4-k-m",
            name = "Qwen3 1.7B",
            variant = "Q4_K_M · 1,28 GB",
            description = "Qwen3 pequeno com bom equilíbrio entre tamanho, velocidade e capacidade geral.",
            fileName = "Qwen3-1.7B-Q4_K_M.gguf",
            approximateSizeBytes = 1_280_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/Qwen3-1.7B-GGUF/resolve/main/Qwen3-1.7B-Q4_K_M.gguf?download=true",
            source = "ggml-org/Qwen3-1.7B-GGUF",
            license = "Apache-2.0",
            recommended = true,
        ),
        CatalogModel(
            id = "smollm3-3b-q4-k-m",
            name = "SmolLM3 3B",
            variant = "Q4_K_M · 1,92 GB",
            description = "Modelo compacto da Hugging Face com foco em boa capacidade dentro de poucos gigabytes.",
            fileName = "SmolLM3-Q4_K_M.gguf",
            approximateSizeBytes = 1_920_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/SmolLM3-3B-GGUF/resolve/main/SmolLM3-Q4_K_M.gguf?download=true",
            source = "ggml-org/SmolLM3-3B-GGUF",
            license = "Apache-2.0",
            recommended = true,
        ),
        CatalogModel(
            id = "llama32-3b-q4-k-m",
            name = "Llama 3.2 3B Instruct",
            variant = "Q4_K_M · 2,02 GB",
            description = "Llama 3.2 instruído de 3B, ainda pequeno o bastante para muitos aparelhos modernos.",
            fileName = "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
            approximateSizeBytes = 2_020_000_000L,
            downloadUrl = "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf?download=true",
            source = "bartowski/Llama-3.2-3B-Instruct-GGUF",
            license = "Llama 3.2 Community License",
        ),
        CatalogModel(
            id = "ministral3-3b-q4-k-m",
            name = "Ministral 3 3B Instruct",
            variant = "Q4_K_M · 2,15 GB",
            description = "Modelo compacto da Mistral AI. O arquivo principal funciona para chat em texto sem o mmproj opcional.",
            fileName = "Ministral-3-3B-Instruct-2512-Q4_K_M.gguf",
            approximateSizeBytes = 2_150_000_000L,
            downloadUrl = "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-GGUF/resolve/main/Ministral-3-3B-Instruct-2512-Q4_K_M.gguf?download=true",
            source = "mistralai/Ministral-3-3B-Instruct-2512-GGUF",
            license = "Apache-2.0",
            recommended = true,
        ),
        CatalogModel(
            id = "phi4-mini-q4-k-m",
            name = "Phi-4 Mini Instruct",
            variant = "Q4_K_M · 2,49 GB",
            description = "Modelo compacto da Microsoft, multilíngue e focado em instruções e raciocínio.",
            fileName = "Phi-4-mini-instruct-Q4_K_M.gguf",
            approximateSizeBytes = 2_492_000_000L,
            downloadUrl = "https://huggingface.co/tensorblock/Phi-4-mini-instruct-GGUF/resolve/main/Phi-4-mini-instruct-Q4_K_M.gguf?download=true",
            source = "tensorblock/Phi-4-mini-instruct-GGUF",
            license = "MIT",
            recommended = true,
        ),
        CatalogModel(
            id = "gemma3-4b-it-q4-k-m",
            name = "Gemma 3 4B IT",
            variant = "Q4_K_M · 2,49 GB",
            description = "Gemma 3 de 4B instruído. Boa opção intermediária para qualidade sem chegar aos modelos de 5–10 GB.",
            fileName = "gemma-3-4b-it-Q4_K_M.gguf",
            approximateSizeBytes = 2_490_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q4_K_M.gguf?download=true",
            source = "ggml-org/gemma-3-4b-it-GGUF",
            license = "Gemma License",
            recommended = true,
        ),
        CatalogModel(
            id = "qwen3-4b-q4-k-m",
            name = "Qwen3 4B",
            variant = "Q4_K_M · 2,50 GB",
            description = "Qwen3 de 4B em quantização equilibrada. Bom ponto intermediário para celulares com mais RAM.",
            fileName = "Qwen3-4B-Q4_K_M.gguf",
            approximateSizeBytes = 2_500_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf?download=true",
            source = "ggml-org/Qwen3-4B-GGUF",
            license = "Apache-2.0",
            recommended = true,
        ),
        CatalogModel(
            id = "deepseek-r1-distill-qwen7b-q4-k-m",
            name = "DeepSeek R1 Distill Qwen 7B",
            variant = "Q4_K_M · 4,68 GB",
            description = "Versão destilada do DeepSeek R1 sobre Qwen 7B, voltada a raciocínio em tamanho bem menor.",
            fileName = "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
            approximateSizeBytes = 4_680_000_000L,
            downloadUrl = "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf?download=true",
            source = "bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF",
            license = "MIT",
        ),
        CatalogModel(
            id = "gemma4-e4b-it-q4-0",
            name = "Gemma 4 E4B",
            variant = "Q4_0 · 4,59 GB",
            description = "Gemma 4 instruído em quantização oficial de 4 bits. O contexto será calibrado automaticamente no aparelho.",
            fileName = "gemma-4-E4B-it-Q4_0.gguf",
            approximateSizeBytes = 4_590_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q4_0.gguf?download=true",
            source = "ggml-org/gemma-4-E4B-it-GGUF",
            license = "Apache-2.0",
            recommended = true,
        ),
        CatalogModel(
            id = "granite33-8b-q4-k-m",
            name = "Granite 3.3 8B Instruct",
            variant = "Q4_K_M · 4,94 GB",
            description = "Modelo IBM Granite de 8B instruído, com licença permissiva e foco em uso geral e empresarial.",
            fileName = "granite-3.3-8b-instruct-Q4_K_M.gguf",
            approximateSizeBytes = 4_940_000_000L,
            downloadUrl = "https://huggingface.co/ibm-granite/granite-3.3-8b-instruct-GGUF/resolve/main/granite-3.3-8b-instruct-Q4_K_M.gguf?download=true",
            source = "ibm-granite/granite-3.3-8b-instruct-GGUF",
            license = "Apache-2.0",
        ),
        CatalogModel(
            id = "qwen3-8b-q4-k-m",
            name = "Qwen3 8B",
            variant = "Q4_K_M · 5,03 GB",
            description = "Opção de 8B disponível para celular. Boa qualidade com cerca de 5 GB de armazenamento.",
            fileName = "Qwen3-8B-Q4_K_M.gguf",
            approximateSizeBytes = 5_030_000_000L,
            downloadUrl = "https://huggingface.co/Qwen/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf?download=true",
            source = "Qwen/Qwen3-8B-GGUF",
            license = "Apache-2.0",
            recommended = true,
        ),
        CatalogModel(
            id = "ministral3-8b-q4-k-m",
            name = "Ministral 3 8B Instruct",
            variant = "Q4_K_M · 5,20 GB",
            description = "Versão de 8B do Ministral 3. Mais pesada, mas ainda dentro da faixa de muitos aparelhos topo de linha.",
            fileName = "Ministral-3-8B-Instruct-2512-Q4_K_M.gguf",
            approximateSizeBytes = 5_200_000_000L,
            downloadUrl = "https://huggingface.co/mistralai/Ministral-3-8B-Instruct-2512-GGUF/resolve/main/Ministral-3-8B-Instruct-2512-Q4_K_M.gguf?download=true",
            source = "mistralai/Ministral-3-8B-Instruct-2512-GGUF",
            license = "Apache-2.0",
        ),
        CatalogModel(
            id = "qwen3-14b-q4-k-m",
            name = "Qwen3 14B",
            variant = "Q4_K_M · 9,00 GB",
            description = "Qwen3 de 14B. Requer aparelho com bastante RAM e armazenamento; o contexto é calibrado automaticamente.",
            fileName = "Qwen3-14B-Q4_K_M.gguf",
            approximateSizeBytes = 9_000_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/Qwen3-14B-GGUF/resolve/main/Qwen3-14B-Q4_K_M.gguf?download=true",
            source = "ggml-org/Qwen3-14B-GGUF",
            license = "Apache-2.0",
        ),
        CatalogModel(
            id = "gpt-oss-20b-mxfp4",
            name = "GPT-OSS 20B",
            variant = "MXFP4 · 12,1 GB",
            description = "Modelo aberto de 20B parâmetros. A quantização MXFP4 oficial reduz o arquivo, mas ainda exige hardware forte.",
            fileName = "gpt-oss-20b-MXFP4.gguf",
            approximateSizeBytes = 12_100_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-MXFP4.gguf?download=true",
            source = "ggml-org/gpt-oss-20b-GGUF",
            license = "Apache-2.0",
        ),
        CatalogModel(
            id = "mistral-small31-24b-q4-k-m",
            name = "Mistral Small 3.1 24B",
            variant = "Q4_K_M · 14,3 GB",
            description = "Modelo Mistral de 24B em Q4_K_M. Muito pesado para celulares comuns, indicado apenas para aparelhos com muita memória.",
            fileName = "mistralai_Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf",
            approximateSizeBytes = 14_330_000_000L,
            downloadUrl = "https://huggingface.co/bartowski/mistralai_Mistral-Small-3.1-24B-Instruct-2503-GGUF/resolve/main/mistralai_Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf?download=true",
            source = "bartowski/mistralai_Mistral-Small-3.1-24B-Instruct-2503-GGUF",
            license = "Apache-2.0",
        ),
        CatalogModel(
            id = "qwen38-27b-q4-k-m",
            name = "Qwen3.8 27B",
            variant = "Q4_K_M · 19,0 GB",
            description = "Modelo de 27B parâmetros. Exige bem mais RAM e armazenamento; o contexto será calibrado automaticamente para o aparelho.",
            fileName = "Qwen3.8-27B-Q4_K_M.gguf",
            approximateSizeBytes = 19_000_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/Qwen3.8-27B-GGUF/resolve/main/Qwen3.8-27B-Q4_K_M.gguf?download=true",
            source = "ggml-org/Qwen3.8-27B-GGUF",
            license = "Apache-2.0",
        ),
        CatalogModel(
            id = "qwen3-32b-q4-k-m",
            name = "Qwen3 32B",
            variant = "Q4_K_M · 19,8 GB",
            description = "Qwen3 denso de 32B. Somente aparelhos com muita RAM terão chance de executá-lo com contexto útil.",
            fileName = "Qwen3-32B-Q4_K_M.gguf",
            approximateSizeBytes = 19_800_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/Qwen3-32B-GGUF/resolve/main/Qwen3-32B-Q4_K_M.gguf?download=true",
            source = "ggml-org/Qwen3-32B-GGUF",
            license = "Apache-2.0",
        ),
        CatalogModel(
            id = "llama4-scout-iq1-s",
            name = "Llama 4 Scout",
            variant = "UD-IQ1_S · 32,5 GB",
            description = "Versão de arquivo único do Llama 4 Scout. É muito grande para a maioria dos celulares; use apenas em aparelhos com armazenamento e RAM excepcionais.",
            fileName = "Llama-4-Scout-17B-16E-Instruct-UD-IQ1_S.gguf",
            approximateSizeBytes = 32_500_000_000L,
            downloadUrl = "https://huggingface.co/ggml-org/Llama-4-Scout-17B-16E-Instruct-GGUF/resolve/main/Llama-4-Scout-17B-16E-Instruct-UD-IQ1_S.gguf?download=true",
            source = "ggml-org/Llama-4-Scout-17B-16E-Instruct-GGUF",
            license = "Llama 4 Community License",
        ),
    )

    fun byId(id: String): CatalogModel? = items.firstOrNull { it.id == id }
}
